### ISSUE TITLE
UE is not defined 以及 不能显示数学公式

### ISSUE THREAD

**Issue by 2010hexi** [zhangkai0621/vue-math-edit#2]
运行启动后，报下面错误
```
Uncaught ReferenceError: UE is not defined
    at window.onload ((index):43)
window.onload @ (index):43
load (async)
(anonymous) @ (index):42
```
![image](https://user-images.githubusercontent.com/43429845/85056602-0eeec900-b1d2-11ea-8ef3-b2cb128b8b2a.png)

并不能显示数学公式

![image](https://user-images.githubusercontent.com/43429845/85056571-ff6f8000-b1d1-11ea-916c-75dbd67b0658.png)

**Comment by zhangkai0621** [comment]
再拉下代码试下

**Comment by zhangkai0621** [comment]
已更新。
